"""Artifact bundle generation: the 'glass box' deliverable.

Produces a zip containing the fitted model, a standalone human-readable
training script that reproduces the run, a FastAPI inference stub, and a
README. The generated code has no dependency on this service.
"""

import shutil
from pathlib import Path
from typing import Any

import joblib

from ..config import ARTIFACTS_DIR
from .pipeline import RunOutcome

# NOTE: the generators below emit the tabular-supervised bundle (sklearn pipeline
# train.py / serve.py). Per-family artifact templates (e.g. a forecasting or torch
# serve stub) are a future extension point keyed off outcome.meta["task_family"].


def _fmt(obj: Any) -> str:
    return repr(obj)


def _generate_train_py(outcome: RunOutcome, plan: dict) -> str:
    spec = outcome.meta["spec"]
    module_path, class_name = spec["model"]["class"].rsplit(".", 1)
    params = {**spec["model"].get("params", {}), **outcome.meta["best_params"]}
    scale = spec["preprocessing"]["numeric"].get("scale", False)
    num_impute = spec["preprocessing"]["numeric"]["impute"]
    cat_impute = spec["preprocessing"]["categorical"]["impute"]
    is_classification = plan["task_type"] != "regression"

    scale_import = ", StandardScaler" if scale else ""
    scale_step = '\n        ("scale", StandardScaler()),' if scale else ""
    if is_classification:
        eval_imports = "from sklearn.metrics import accuracy_score, roc_auc_score\nfrom sklearn.preprocessing import LabelEncoder"
        target_prep = """    label_encoder = LabelEncoder()
    y = label_encoder.fit_transform(df[TARGET].astype(str))"""
        eval_block = """    y_pred = model.predict(X_test)
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    if len(label_encoder.classes_) == 2:
        y_proba = model.predict_proba(X_test)[:, 1]
        print(f"ROC-AUC:  {roc_auc_score(y_test, y_proba):.4f}")"""
        stratify = ", stratify=y"
        meta_extra = '"label_classes": [str(c) for c in label_encoder.classes_],'
    else:
        eval_imports = "from sklearn.metrics import mean_absolute_error, r2_score"
        target_prep = "    y = df[TARGET].astype(float)"
        eval_block = """    y_pred = model.predict(X_test)
    print(f"R2:  {r2_score(y_test, y_pred):.4f}")
    print(f"MAE: {mean_absolute_error(y_test, y_pred):.4f}")"""
        stratify = ""
        meta_extra = '"label_classes": None,'

    return f'''"""Standalone training script generated by Model Builder.

Methodology: {spec["display_name"]} ({spec["id"]})
Target: {plan["target_column"]} | Task: {plan["task_type"]}

This script is self-contained: edit anything you like and re-run it.
Usage: python train.py path/to/data.csv
"""

import sys

import joblib
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder{scale_import}
{eval_imports}
from {module_path} import {class_name}

TARGET = {_fmt(plan["target_column"])}
NUMERIC_FEATURES = {_fmt(outcome.meta["numeric_columns"])}
CATEGORICAL_FEATURES = {_fmt(outcome.meta["categorical_columns"])}
# Hyperparameters selected by cross-validated grid search
MODEL_PARAMS = {_fmt(params)}


def build_pipeline() -> Pipeline:
    numeric = Pipeline([
        ("impute", SimpleImputer(strategy={_fmt(num_impute)})),{scale_step}
    ])
    categorical = Pipeline([
        ("impute", SimpleImputer(strategy={_fmt(cat_impute)})),
        ("onehot", OneHotEncoder(handle_unknown="ignore", max_categories=30)),
    ])
    preprocess = ColumnTransformer([
        ("num", numeric, NUMERIC_FEATURES),
        ("cat", categorical, CATEGORICAL_FEATURES),
    ], remainder="drop")
    return Pipeline([
        ("preprocess", preprocess),
        ("model", {class_name}(**MODEL_PARAMS)),
    ])


def main(csv_path: str) -> None:
    df = pd.read_csv(csv_path).dropna(subset=[TARGET])
    X = df[NUMERIC_FEATURES + CATEGORICAL_FEATURES]
{target_prep}

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42{stratify}
    )
    model = build_pipeline()
    model.fit(X_train, y_train)

{eval_block}

    joblib.dump(
        {{
            "pipeline": model,
            "meta": {{
                "feature_columns": NUMERIC_FEATURES + CATEGORICAL_FEATURES,
                "target_column": TARGET,
                "task_type": {_fmt(plan["task_type"])},
                {meta_extra}
            }},
        }},
        "model.joblib",
    )
    print("Saved model.joblib")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "data.csv")
'''


def _generate_serve_py(plan: dict) -> str:
    is_classification = plan["task_type"] != "regression"
    if is_classification:
        predict_body = '''    preds = pipeline.predict(X)
    labels = meta.get("label_classes")
    out = {"predictions": [labels[int(p)] if labels else p for p in preds]}
    if hasattr(pipeline, "predict_proba"):
        proba = pipeline.predict_proba(X)
        out["probabilities"] = [
            {labels[j] if labels else str(j): round(float(p), 4) for j, p in enumerate(row)}
            for row in proba
        ]
    return out'''
    else:
        predict_body = '''    preds = pipeline.predict(X)
    return {"predictions": [float(p) for p in preds]}'''

    return f'''"""Inference server stub generated by Model Builder.

Run:  uvicorn serve:app --port 8080
Then: POST /predict with {{"records": [{{"col": value, ...}}]}}
"""

import joblib
import pandas as pd
from fastapi import FastAPI
from pydantic import BaseModel

bundle = joblib.load("model.joblib")
pipeline, meta = bundle["pipeline"], bundle["meta"]

app = FastAPI(title="Model inference")


class PredictRequest(BaseModel):
    records: list[dict]


@app.post("/predict")
def predict(req: PredictRequest) -> dict:
    # Missing columns become NaN and flow through the pipeline's imputers.
    X = pd.DataFrame(req.records).reindex(columns=meta["feature_columns"])
{predict_body}
'''


def _metric_lines(results: dict) -> str:
    """Holdout metric bullets vs baseline; shared by supervised and forecasting READMEs."""
    return "\n".join(
        f"- {name}: {value} (baseline: {results['holdout']['baseline_metrics'].get(name, 'n/a')})"
        for name, value in results["holdout"]["metrics"].items()
    )


def _generate_readme(outcome: RunOutcome, plan: dict, results: dict) -> str:
    spec = outcome.meta["spec"]
    metrics_lines = _metric_lines(results)
    return f"""# Model bundle: {spec["display_name"]}

Trained on target `{plan["target_column"]}` ({plan["task_type"]}).

## Files

- `model.joblib` — fitted sklearn pipeline (preprocessing + model) with metadata
- `train.py` — standalone script that reproduces this training run; edit freely
- `serve.py` — FastAPI inference server stub
- `requirements.txt` — dependencies for the scripts above

## Holdout metrics (20% test split)

{metrics_lines}

Baseline = {results["holdout"]["baseline_description"]}.

## Quick start

```
pip install -r requirements.txt
python train.py your_data.csv       # retrain from scratch
uvicorn serve:app --port 8080       # serve the bundled model
```

## Selected hyperparameters

{outcome.meta["best_params"]}

Generated by Model Builder.
"""


# --------------------------------------------------------------------------- #
# Forecasting generators (task_family == "forecasting")                        #
# --------------------------------------------------------------------------- #
def _generate_train_py_forecasting(outcome: RunOutcome, plan: dict) -> str:
    spec = outcome.meta["spec"]
    framing = outcome.meta["framing"]
    module_path, class_name = spec["model"]["class"].rsplit(".", 1)
    params = {**spec["model"].get("params", {}), **outcome.meta["best_params"]}
    ts_cfg = spec["preprocessing"]["timeseries"]

    header = f'''"""Standalone forecasting script generated by Model Builder.

Methodology: {spec["display_name"]} ({spec["id"]})
Target: {plan["target_column"]} | Time axis: {outcome.meta["time_column"]} | Horizon: {outcome.meta["horizon"]}

This script is self-contained: edit anything you like and re-run it. It holds out the
last HORIZON rows, fits on the rest, and reports error on that recent window.
Usage: python train.py path/to/data.csv
"""

import sys

import joblib
import numpy as np
import pandas as pd

TARGET = {_fmt(plan["target_column"])}
TIME_COL = {_fmt(outcome.meta["time_column"])}
HORIZON = {_fmt(int(outcome.meta["horizon"]))}
FREQ = {_fmt(outcome.meta["freq"])}
MODEL_PARAMS = {_fmt(params)}


def _errors(actual, pred):
    actual, pred = np.asarray(actual, float), np.asarray(pred, float)
    mae = float(np.mean(np.abs(actual - pred)))
    mask = actual != 0
    mape = float(np.mean(np.abs((actual[mask] - pred[mask]) / actual[mask])) * 100.0) if mask.any() else None
    return mae, mape


def _load(csv_path):
    df = pd.read_csv(csv_path).dropna(subset=[TARGET])
    df[TIME_COL] = pd.to_datetime(df[TIME_COL], errors="coerce")
    df = df.dropna(subset=[TIME_COL]).sort_values(TIME_COL).reset_index(drop=True)
    return df
'''

    if framing == "prophet":
        body = f'''

def main(csv_path: str) -> None:
    from {module_path} import {class_name}

    df = _load(csv_path)
    n_train = len(df) - HORIZON
    train, holdout = df.iloc[:n_train], df.iloc[n_train:]

    model = {class_name}(**MODEL_PARAMS)
    model.fit(pd.DataFrame({{"ds": train[TIME_COL].to_numpy(), "y": train[TARGET].astype(float).to_numpy()}}))

    fc = model.predict(pd.DataFrame({{"ds": holdout[TIME_COL].to_numpy()}}))
    mae, mape = _errors(holdout[TARGET].to_numpy(), fc["yhat"].to_numpy())
    print(f"Holdout MAE:  {{mae:.4f}}")
    print(f"Holdout MAPE: {{mape:.2f}}%" if mape is not None else "Holdout MAPE: n/a")

    joblib.dump(
        {{
            "pipeline": model,
            "meta": {{
                "target_column": TARGET,
                "time_column": TIME_COL,
                "horizon": HORIZON,
                "freq": FREQ,
                "framing": "prophet",
                "task_type": "forecasting",
                "task_family": "forecasting",
                "feature_columns": [],
            }},
        }},
        "model.joblib",
    )
    print("Saved model.joblib")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "data.csv")
'''
        return header + body

    # lag_features: rebuild the lag / rolling / calendar features the runner uses.
    lags = ts_cfg.get("lags", [1, 2, 3, 7, 14])
    rolling = ts_cfg.get("rolling_windows", [7])
    calendar = ts_cfg.get("calendar_features", True)
    body = f'''LAGS = {_fmt(lags)}
ROLLING_WINDOWS = {_fmt(rolling)}
CALENDAR_FEATURES = {_fmt(calendar)}


def _build_lag_matrix(y, ts, lags, rolling, calendar):
    """Trailing lag / rolling-mean / calendar features (rolling means are shifted by one
    step so a row never sees its own target — no leakage)."""
    start = max([max(lags) if lags else 0] + [max(rolling) if rolling else 0])
    rows, targets = [], []
    for i in range(start, len(y)):
        feats = [y[i - l] for l in lags]
        feats += [float(np.mean(y[i - w:i])) for w in rolling]
        if calendar:
            t = ts[i]
            feats += [t.dayofweek, t.day, t.month]
        rows.append(feats)
        targets.append(y[i])
    return np.asarray(rows, float), np.asarray(targets, float)


def _recursive_forecast(model, hist_y, future_ts, lags, rolling, calendar):
    """Predict one step, append it, rebuild features, repeat. Error compounds."""
    work = list(hist_y)
    preds = []
    for t in future_ts:
        i = len(work)
        feats = [work[i - l] for l in lags]
        feats += [float(np.mean(work[i - w:i])) for w in rolling]
        if calendar:
            feats += [t.dayofweek, t.day, t.month]
        p = float(model.predict(np.asarray([feats], float))[0])
        preds.append(p)
        work.append(p)
    return np.asarray(preds, float)


def main(csv_path: str) -> None:
    from {module_path} import {class_name}

    df = _load(csv_path)
    y = df[TARGET].astype(float).to_numpy()
    ts = pd.DatetimeIndex(df[TIME_COL])
    n_train = len(y) - HORIZON
    train_y, holdout_y = y[:n_train], y[n_train:]
    train_ts, holdout_ts = ts[:n_train], ts[n_train:]

    lags = [l for l in LAGS if l < len(train_y)]
    rolling = [w for w in ROLLING_WINDOWS if w < len(train_y)]
    X, target = _build_lag_matrix(train_y, train_ts, lags, rolling, CALENDAR_FEATURES)

    model = {class_name}(**MODEL_PARAMS)
    model.fit(X, target)

    pred = _recursive_forecast(model, train_y, holdout_ts, lags, rolling, CALENDAR_FEATURES)
    mae, mape = _errors(holdout_y, pred)
    print(f"Holdout MAE:  {{mae:.4f}}")
    print(f"Holdout MAPE: {{mape:.2f}}%" if mape is not None else "Holdout MAPE: n/a")

    tail_len = (max(lags + rolling) if (lags + rolling) else 0) + 1
    joblib.dump(
        {{
            "pipeline": {{
                "model": model,
                "lags": lags,
                "rolling_windows": rolling,
                "calendar_features": CALENDAR_FEATURES,
                "history_tail": pd.DataFrame(
                    {{TIME_COL: ts[-tail_len:], TARGET: y[-tail_len:]}}
                ).reset_index(drop=True),
            }},
            "meta": {{
                "target_column": TARGET,
                "time_column": TIME_COL,
                "horizon": HORIZON,
                "freq": FREQ,
                "framing": "lag_features",
                "task_type": "forecasting",
                "task_family": "forecasting",
                "feature_columns": {_fmt(outcome.meta["feature_columns"])},
            }},
        }},
        "model.joblib",
    )
    print("Saved model.joblib")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "data.csv")
'''
    return header + body


def _generate_serve_py_forecasting(plan: dict) -> str:
    return '''"""Forecast server stub generated by Model Builder.

Run:  uvicorn serve:app --port 8080
Then: GET /forecast?horizon=30   (defaults to the trained horizon)

`forecast(horizon)` continues the series past the last observed timestamp and returns
future timestamps, point forecasts (yhat), and — where available — interval bounds.
"""

import numpy as np
import pandas as pd
import joblib
from fastapi import FastAPI

bundle = joblib.load("model.joblib")
artifact, meta = bundle["pipeline"], bundle["meta"]

app = FastAPI(title="Forecast inference")


def _future_timestamps(last, horizon: int):
    freq = meta.get("freq")
    if freq:
        try:
            return pd.date_range(start=last, periods=horizon + 1, freq=freq)[1:]
        except (ValueError, TypeError):
            pass
    return pd.DatetimeIndex([pd.Timestamp(last) + pd.Timedelta(days=i + 1) for i in range(horizon)])


def forecast(horizon: int | None = None) -> dict:
    horizon = int(horizon or meta["horizon"])
    if meta["framing"] == "prophet":
        model = artifact
        future = model.make_future_dataframe(periods=horizon, freq=meta.get("freq") or "D", include_history=False)
        fc = model.predict(future).tail(horizon)
        return {
            "timestamps": [pd.Timestamp(t).isoformat() for t in fc["ds"]],
            "yhat": [round(float(v), 4) for v in fc["yhat"]],
            "lower": [round(float(v), 4) for v in fc["yhat_lower"]],
            "upper": [round(float(v), 4) for v in fc["yhat_upper"]],
        }

    # lag_features: seed recursive prediction from the bundled history tail.
    model = artifact["model"]
    lags, rolling = artifact["lags"], artifact["rolling_windows"]
    calendar = artifact["calendar_features"]
    hist = artifact["history_tail"]
    hist_y = hist[meta["target_column"]].astype(float).to_numpy()
    last_ts = pd.Timestamp(hist[meta["time_column"]].iloc[-1])
    future_ts = _future_timestamps(last_ts, horizon)

    work = list(hist_y)
    preds = []
    for t in future_ts:
        i = len(work)
        feats = [work[i - l] for l in lags]
        feats += [float(np.mean(work[i - w:i])) for w in rolling]
        if calendar:
            feats += [t.dayofweek, t.day, t.month]
        p = float(model.predict(np.asarray([feats], float))[0])
        preds.append(round(p, 4))
        work.append(p)
    return {
        "timestamps": [pd.Timestamp(t).isoformat() for t in future_ts],
        "yhat": preds,
    }


@app.get("/forecast")
def forecast_endpoint(horizon: int | None = None) -> dict:
    return forecast(horizon)
'''


def _generate_readme_forecasting(outcome: RunOutcome, plan: dict, results: dict) -> str:
    spec = outcome.meta["spec"]
    metrics_lines = _metric_lines(results)
    fc = results["forecast"]
    first_ts, last_ts = fc["timestamps"][0], fc["timestamps"][-1]
    first_yhat, last_yhat = fc["yhat"][0], fc["yhat"][-1]
    caveats = "\n".join(f"- {c}" for c in results["caveats"])
    return f"""# Forecast bundle: {spec["display_name"]}

Forecasts target `{plan["target_column"]}` over time axis `{outcome.meta["time_column"]}`.

- Horizon: {outcome.meta["horizon"]} periods
- Frequency: {outcome.meta["freq"]}

## Files

- `model.joblib` — fitted forecasting model + metadata
- `train.py` — standalone script that reproduces this run; edit freely
- `serve.py` — FastAPI server exposing `forecast(horizon)`
- `requirements.txt` — dependencies for the scripts above

## Holdout metrics (last {outcome.meta["horizon"]} periods)

{metrics_lines}

Baseline = {results["holdout"]["baseline_description"]}. All forecasting metrics are
lower-is-better; MASE < 1 beats the seasonal-naive baseline.

## Forecast

The `forecast` block covers the future horizon, from {first_ts} ({first_yhat}) to
{last_ts} ({last_yhat}).

## Caveats

{caveats}

## Quick start

```
pip install -r requirements.txt
python train.py your_data.csv       # retrain from scratch
uvicorn serve:app --port 8080       # serve forecasts
```

## Selected hyperparameters

{outcome.meta["best_params"]}

Generated by Model Builder.
"""


def build_bundle(run_id: str, outcome: RunOutcome, plan: dict) -> str:
    """Write the bundle directory and zip it. Returns the zip path."""
    results = outcome.results
    task_family = outcome.meta["task_family"]
    bundle_dir = ARTIFACTS_DIR / run_id / "bundle"
    if bundle_dir.exists():
        shutil.rmtree(bundle_dir)
    bundle_dir.mkdir(parents=True)

    meta = {
        "feature_columns": outcome.meta["feature_columns"],
        "target_column": plan["target_column"],
        "task_type": plan["task_type"],
        "label_classes": outcome.meta["label_classes"],
        "methodology_id": plan["methodology_id"],
        "data_shape": outcome.meta["data_shape"],
        "task_family": task_family,
    }
    if task_family == "forecasting":
        meta.update(
            {
                "time_column": outcome.meta["time_column"],
                "horizon": outcome.meta["horizon"],
                "freq": outcome.meta["freq"],
                "framing": outcome.meta["framing"],
            }
        )

    joblib.dump({"pipeline": outcome.artifact, "meta": meta}, bundle_dir / "model.joblib")

    if task_family == "forecasting":
        train_py = _generate_train_py_forecasting(outcome, plan)
        serve_py = _generate_serve_py_forecasting(plan)
        readme = _generate_readme_forecasting(outcome, plan, results)
    else:
        train_py = _generate_train_py(outcome, plan)
        serve_py = _generate_serve_py(plan)
        readme = _generate_readme(outcome, plan, results)

    (bundle_dir / "train.py").write_text(train_py, encoding="utf-8")
    (bundle_dir / "serve.py").write_text(serve_py, encoding="utf-8")
    (bundle_dir / "README.md").write_text(readme, encoding="utf-8")

    reqs = ["scikit-learn>=1.6", "pandas>=2.2", "joblib>=1.4", "fastapi>=0.115", "uvicorn>=0.32"]
    # sklearn model classes need nothing extra; non-sklearn libraries pin their own line.
    extra_reqs = {"lightgbm": "lightgbm>=4.5", "xgboost": "xgboost>=3.3", "prophet": "prophet>=1.3"}
    top_module = outcome.meta["spec"]["model"]["class"].split(".")[0]
    if top_module in extra_reqs:
        reqs.insert(0, extra_reqs[top_module])
    (bundle_dir / "requirements.txt").write_text("\n".join(reqs) + "\n", encoding="utf-8")

    zip_base = str(ARTIFACTS_DIR / run_id / "model_bundle")
    zip_path = shutil.make_archive(zip_base, "zip", bundle_dir)
    return zip_path
