"""Artifact bundle generation: the 'glass box' deliverable.

Produces a zip containing the fitted model, a standalone human-readable
training script that reproduces the run, a FastAPI inference stub, and a
README. The generated code has no dependency on this service.
"""

import shutil
from pathlib import Path
from typing import Any

import joblib

from ..config import ARTIFACTS_DIR
from .pipeline import RunOutcome

# NOTE: the generators below emit the tabular-supervised bundle (sklearn pipeline
# train.py / serve.py). Per-family artifact templates (e.g. a forecasting or torch
# serve stub) are a future extension point keyed off outcome.meta["task_family"].


def _fmt(obj: Any) -> str:
    return repr(obj)


def _generate_train_py(outcome: RunOutcome, plan: dict) -> str:
    spec = outcome.meta["spec"]
    module_path, class_name = spec["model"]["class"].rsplit(".", 1)
    params = {**spec["model"].get("params", {}), **outcome.meta["best_params"]}
    scale = spec["preprocessing"]["numeric"].get("scale", False)
    num_impute = spec["preprocessing"]["numeric"]["impute"]
    cat_impute = spec["preprocessing"]["categorical"]["impute"]
    is_classification = plan["task_type"] != "regression"

    scale_import = ", StandardScaler" if scale else ""
    scale_step = '\n        ("scale", StandardScaler()),' if scale else ""
    if is_classification:
        eval_imports = "from sklearn.metrics import accuracy_score, roc_auc_score\nfrom sklearn.preprocessing import LabelEncoder"
        target_prep = """    label_encoder = LabelEncoder()
    y = label_encoder.fit_transform(df[TARGET].astype(str))"""
        eval_block = """    y_pred = model.predict(X_test)
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    if len(label_encoder.classes_) == 2:
        y_proba = model.predict_proba(X_test)[:, 1]
        print(f"ROC-AUC:  {roc_auc_score(y_test, y_proba):.4f}")"""
        stratify = ", stratify=y"
        meta_extra = '"label_classes": [str(c) for c in label_encoder.classes_],'
    else:
        eval_imports = "from sklearn.metrics import mean_absolute_error, r2_score"
        target_prep = "    y = df[TARGET].astype(float)"
        eval_block = """    y_pred = model.predict(X_test)
    print(f"R2:  {r2_score(y_test, y_pred):.4f}")
    print(f"MAE: {mean_absolute_error(y_test, y_pred):.4f}")"""
        stratify = ""
        meta_extra = '"label_classes": None,'

    return f'''"""Standalone training script generated by Model Builder.

Methodology: {spec["display_name"]} ({spec["id"]})
Target: {plan["target_column"]} | Task: {plan["task_type"]}

This script is self-contained: edit anything you like and re-run it.
Usage: python train.py path/to/data.csv
"""

import sys

import joblib
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder{scale_import}
{eval_imports}
from {module_path} import {class_name}

TARGET = {_fmt(plan["target_column"])}
NUMERIC_FEATURES = {_fmt(outcome.meta["numeric_columns"])}
CATEGORICAL_FEATURES = {_fmt(outcome.meta["categorical_columns"])}
# Hyperparameters selected by cross-validated grid search
MODEL_PARAMS = {_fmt(params)}


def build_pipeline() -> Pipeline:
    numeric = Pipeline([
        ("impute", SimpleImputer(strategy={_fmt(num_impute)})),{scale_step}
    ])
    categorical = Pipeline([
        ("impute", SimpleImputer(strategy={_fmt(cat_impute)})),
        ("onehot", OneHotEncoder(handle_unknown="ignore", max_categories=30)),
    ])
    preprocess = ColumnTransformer([
        ("num", numeric, NUMERIC_FEATURES),
        ("cat", categorical, CATEGORICAL_FEATURES),
    ], remainder="drop")
    return Pipeline([
        ("preprocess", preprocess),
        ("model", {class_name}(**MODEL_PARAMS)),
    ])


def main(csv_path: str) -> None:
    df = pd.read_csv(csv_path).dropna(subset=[TARGET])
    X = df[NUMERIC_FEATURES + CATEGORICAL_FEATURES]
{target_prep}

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42{stratify}
    )
    model = build_pipeline()
    model.fit(X_train, y_train)

{eval_block}

    joblib.dump(
        {{
            "pipeline": model,
            "meta": {{
                "feature_columns": NUMERIC_FEATURES + CATEGORICAL_FEATURES,
                "target_column": TARGET,
                "task_type": {_fmt(plan["task_type"])},
                {meta_extra}
            }},
        }},
        "model.joblib",
    )
    print("Saved model.joblib")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "data.csv")
'''


def _generate_serve_py(plan: dict) -> str:
    is_classification = plan["task_type"] != "regression"
    if is_classification:
        predict_body = '''    preds = pipeline.predict(X)
    labels = meta.get("label_classes")
    out = {"predictions": [labels[int(p)] if labels else p for p in preds]}
    if hasattr(pipeline, "predict_proba"):
        proba = pipeline.predict_proba(X)
        out["probabilities"] = [
            {labels[j] if labels else str(j): round(float(p), 4) for j, p in enumerate(row)}
            for row in proba
        ]
    return out'''
    else:
        predict_body = '''    preds = pipeline.predict(X)
    return {"predictions": [float(p) for p in preds]}'''

    return f'''"""Inference server stub generated by Model Builder.

Run:  uvicorn serve:app --port 8080
Then: POST /predict with {{"records": [{{"col": value, ...}}]}}
"""

import joblib
import pandas as pd
from fastapi import FastAPI
from pydantic import BaseModel

bundle = joblib.load("model.joblib")
pipeline, meta = bundle["pipeline"], bundle["meta"]

app = FastAPI(title="Model inference")


class PredictRequest(BaseModel):
    records: list[dict]


@app.post("/predict")
def predict(req: PredictRequest) -> dict:
    # Missing columns become NaN and flow through the pipeline's imputers.
    X = pd.DataFrame(req.records).reindex(columns=meta["feature_columns"])
{predict_body}
'''


def _generate_readme(outcome: RunOutcome, plan: dict, results: dict) -> str:
    spec = outcome.meta["spec"]
    metrics_lines = "\n".join(
        f"- {name}: {value} (baseline: {results['holdout']['baseline_metrics'].get(name, 'n/a')})"
        for name, value in results["holdout"]["metrics"].items()
    )
    return f"""# Model bundle: {spec["display_name"]}

Trained on target `{plan["target_column"]}` ({plan["task_type"]}).

## Files

- `model.joblib` — fitted sklearn pipeline (preprocessing + model) with metadata
- `train.py` — standalone script that reproduces this training run; edit freely
- `serve.py` — FastAPI inference server stub
- `requirements.txt` — dependencies for the scripts above

## Holdout metrics (20% test split)

{metrics_lines}

Baseline = {results["holdout"]["baseline_description"]}.

## Quick start

```
pip install -r requirements.txt
python train.py your_data.csv       # retrain from scratch
uvicorn serve:app --port 8080       # serve the bundled model
```

## Selected hyperparameters

{outcome.meta["best_params"]}

Generated by Model Builder.
"""


def build_bundle(run_id: str, outcome: RunOutcome, plan: dict) -> str:
    """Write the bundle directory and zip it. Returns the zip path."""
    results = outcome.results
    bundle_dir = ARTIFACTS_DIR / run_id / "bundle"
    if bundle_dir.exists():
        shutil.rmtree(bundle_dir)
    bundle_dir.mkdir(parents=True)

    joblib.dump(
        {
            "pipeline": outcome.artifact,
            "meta": {
                "feature_columns": outcome.meta["feature_columns"],
                "target_column": plan["target_column"],
                "task_type": plan["task_type"],
                "label_classes": outcome.meta["label_classes"],
                "methodology_id": plan["methodology_id"],
                "data_shape": outcome.meta["data_shape"],
                "task_family": outcome.meta["task_family"],
            },
        },
        bundle_dir / "model.joblib",
    )

    (bundle_dir / "train.py").write_text(_generate_train_py(outcome, plan), encoding="utf-8")
    (bundle_dir / "serve.py").write_text(_generate_serve_py(plan), encoding="utf-8")
    (bundle_dir / "README.md").write_text(_generate_readme(outcome, plan, results), encoding="utf-8")

    reqs = ["scikit-learn>=1.6", "pandas>=2.2", "joblib>=1.4", "fastapi>=0.115", "uvicorn>=0.32"]
    if outcome.meta["spec"]["model"]["class"].startswith("lightgbm"):
        reqs.insert(0, "lightgbm>=4.5")
    (bundle_dir / "requirements.txt").write_text("\n".join(reqs) + "\n", encoding="utf-8")

    zip_base = str(ARTIFACTS_DIR / run_id / "model_bundle")
    zip_path = shutil.make_archive(zip_base, "zip", bundle_dir)
    return zip_path
